//
//  FractalScapeIconSet.h
//  FractalScape
//
//  Created by Taun Chapman on 08/29/15.
//  Copyright (c) 2015 MOEDAE LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>



@interface FractalScapeIconSet : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarLinePropertiesIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarRulesIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarPageColorIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarCopyIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarAppearanceIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarFullScreenIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarFullScreenIconOffTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarCopyIconTintedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDrawLineTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleMoveByLineTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDrawDotTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDecrementLineWidthTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleIncrementLineWidthTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconCurveSymbolTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleClosePolygonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDecrementAngleTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleIncrementAngleTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleRotateCTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleRotateCCTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePushTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePopTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleSwapRotationTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleReverseDirectionTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleFillOnTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleFillOffTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleUpscaleLineLengthTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDownscaleLineLengthTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleStrokeOffTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleStrokeOnTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleRandomizeOffTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleRandomizeOnTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlace0Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlace1Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kbIconRulePlace2Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlace3Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlace4Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlace5Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlaceEmptyTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconBaseAngleTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kPathArrowTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* sKTextureTurtleJointTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kMBFilterBackgroundTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kLibraryCellBackgroundImageTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kMBFilterBackground3Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPad76Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon40Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPadBeta76Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConBeta40Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iCon60Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConBeta60Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPadDebugTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConDebug60Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConDebug40Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConDebug29Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConBeta29Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iCon29Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iCon50Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* documentThumbnailPlaceholder1024Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* premiumUpgradeImageTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* metalPak1UpgradeImageTargets;

// Colors
+ (UIColor*)symbolFillColor;
+ (UIColor*)ruleGhostLineColor;
+ (UIColor*)transformActionColor;
+ (UIColor*)groupBorderColor;
+ (UIColor*)selectionBackgroundColor;
+ (UIColor*)betaColor;
+ (UIColor*)tutorialOverlayColor;
+ (UIColor*)tintColor;
+ (UIColor*)tintColorWithAlpha;

// Shadows
+ (NSShadow*)topShadow;
+ (NSShadow*)dropShadowInner;

// Drawing Methods
+ (void)drawTabBarLinePropertiesIcon;
+ (void)drawTabBarRulesIcon;
+ (void)drawTabBarPageColorIcon;
+ (void)drawToolBarCopyIcon;
+ (void)drawToolBarAppearanceIcon;
+ (void)drawToolBarFullScreenIcon;
+ (void)drawToolBarHUDScreenIconOld;
+ (void)drawToolBarFullScreenIcon2;
+ (void)drawToolBarHUDScreenIcon2;
+ (void)drawToolBarFullScreenIconOff;
+ (void)drawToolBarPlay;
+ (void)drawToolBarDoubleDragSymbolOn;
+ (void)drawToolBarDoubleDragSymbolOff;
+ (void)drawToolBarJointRotationSymbol;
+ (void)drawToolBarIncrementsButtonSymbol;
+ (void)drawToolBarBaseRotationButtonSymbol;
+ (void)drawToolBarPlayTinted;
+ (void)drawToolBarCopyIconTinted;
+ (void)drawKBIconRuleDrawLine;
+ (void)drawKBIconRuleMoveByLine;
+ (void)drawKBIconRuleDrawDot;
+ (void)drawKBIconRuleDecrementLineWidth;
+ (void)drawKBIconRuleIncrementLineWidth;
+ (void)drawKBIconCurveSymbol;
+ (void)drawKBIconRuleClosePolygon;
+ (void)drawKBIconRuleDecrementAngle;
+ (void)drawKBIconRuleIncrementAngle;
+ (void)drawKBIconRuleRotateC;
+ (void)drawKBIconRuleRotateCC;
+ (void)drawKBIconRulePush;
+ (void)drawKBIconRulePop;
+ (void)drawKBIconRuleSwapRotation;
+ (void)drawKBIconRuleReverseDirection;
+ (void)drawKBIconRuleFillOn;
+ (void)drawKBIconRuleFillOff;
+ (void)drawKBIconRuleUpscaleLineLength;
+ (void)drawKBIconRuleDownscaleLineLength;
+ (void)drawKBIconRuleStrokeOff;
+ (void)drawKBIconRuleStrokeOn;
+ (void)drawKBIconRuleRandomizeOff;
+ (void)drawKBIconRuleRandomizeOn;
+ (void)drawKBIconRulePlace0;
+ (void)drawKBIconRulePlace1;
+ (void)drawKbIconRulePlace2;
+ (void)drawKBIconRulePlace3;
+ (void)drawKBIconRulePlace4;
+ (void)drawKBIconRulePlace5;
+ (void)drawElements;
+ (void)drawKBIconRuleDrawDotFilled;
+ (void)drawKBIconRuleNextColor;
+ (void)drawKBIconRulePreviousColor;
+ (void)drawKBIconRulePlaceEmpty;
+ (void)drawKBIconRuleNextFillColor;
+ (void)drawKBIconRulePreviousFillColor;
+ (void)drawKBIconRuleDrawLineVarD;
+ (void)drawKBIconRuleSymbolArrowHead;
+ (void)drawKbIconRuleCurvePoint;
+ (void)drawKBIconRuleCurveC;
+ (void)drawKBIconRuleCurveCC;
+ (void)drawKBIconRulePushOld;
+ (void)drawKBIconRulePullOld;
+ (void)drawKBIconBaseAngle;
+ (void)drawKBIconBaseAngleSmallWithFrame: (CGRect)frame;
+ (void)drawKBIconRuleDecrementAngleSmallWithFrame: (CGRect)frame;
+ (void)drawKBIconRuleRotateCCSmallWithFrame: (CGRect)frame;
+ (void)drawKBIconRuleDrawPath;
+ (void)drawKBIconRuleClosePath;
+ (void)drawKBIconRuleOpenPolygon;
+ (void)drawKBIconRuleDecrementLineWidth90;
+ (void)drawKBIconRuleDrawLineLeft;
+ (void)drawKPathArrow;
+ (void)drawSKTextureTurtleJoint;
+ (void)drawKNorthArrow;
+ (void)drawRatingBarImage;
+ (void)drawRatingStarSymbol;
+ (void)drawKMBFilterBackground;
+ (void)drawKMBFilterBackground2;
+ (void)drawKLibraryCellBackgroundImage;
+ (void)drawKRowDeleteSwipeIcon;
+ (void)drawKRowAddSwipeIcon;
+ (void)drawKMBFilterBackground3;
+ (void)drawAddDeletePrototype;
+ (void)drawKMBFilterBackground4;
+ (void)drawKRowDeleteSwipeIcon2;
+ (void)drawKRowAddSwipeIcon2;
+ (void)drawWatermark;
+ (void)drawLineEditControllerWithFrame: (CGRect)frame;
+ (void)drawKCGLineCapSquareIcon;
+ (void)drawKCGLineCapRoundIcon;
+ (void)drawKCGLineCapButtIcon;
+ (void)drawKCGLineJoinMiterIcon;
+ (void)drawKCGLineJoinRoundIcon;
+ (void)drawKCGLineJoinBevelIcon;
+ (void)drawControlSliderBackgroundWithFrame: (CGRect)frame;
+ (void)drawBetaSymbol;
+ (void)drawAlphaSymbol;
+ (void)drawLowresBushSymbol;
+ (void)drawLowresBushTemplate;
+ (void)drawDocumentThumbnailPlaceholder130;
+ (void)drawLowresBushTemplateTinted;
+ (void)drawIntroArrowDuplicate;
+ (void)drawDefaultIntroArrow2;
+ (void)drawIntroArrowShare;
+ (void)drawIntroArrowPlay;

// Generated Images
+ (UIImage*)imageOfTabBarLinePropertiesIcon;
+ (UIImage*)imageOfTabBarRulesIcon;
+ (UIImage*)imageOfTabBarPageColorIcon;
+ (UIImage*)imageOfToolBarCopyIcon;
+ (UIImage*)imageOfToolBarAppearanceIcon;
+ (UIImage*)imageOfToolBarFullScreenIcon;
+ (UIImage*)imageOfToolBarFullScreenIconOff;
+ (UIImage*)imageOfToolBarCopyIconTinted;
+ (UIImage*)imageOfKBIconRuleDrawLine;
+ (UIImage*)imageOfKBIconRuleMoveByLine;
+ (UIImage*)imageOfKBIconRuleDrawDot;
+ (UIImage*)imageOfKBIconRuleDecrementLineWidth;
+ (UIImage*)imageOfKBIconRuleIncrementLineWidth;
+ (UIImage*)imageOfKBIconCurveSymbol;
+ (UIImage*)imageOfKBIconRuleClosePolygon;
+ (UIImage*)imageOfKBIconRuleDecrementAngle;
+ (UIImage*)imageOfKBIconRuleIncrementAngle;
+ (UIImage*)imageOfKBIconRuleRotateC;
+ (UIImage*)imageOfKBIconRuleRotateCC;
+ (UIImage*)imageOfKBIconRulePush;
+ (UIImage*)imageOfKBIconRulePop;
+ (UIImage*)imageOfKBIconRuleSwapRotation;
+ (UIImage*)imageOfKBIconRuleReverseDirection;
+ (UIImage*)imageOfKBIconRuleFillOn;
+ (UIImage*)imageOfKBIconRuleFillOff;
+ (UIImage*)imageOfKBIconRuleUpscaleLineLength;
+ (UIImage*)imageOfKBIconRuleDownscaleLineLength;
+ (UIImage*)imageOfKBIconRuleStrokeOff;
+ (UIImage*)imageOfKBIconRuleStrokeOn;
+ (UIImage*)imageOfKBIconRuleRandomizeOff;
+ (UIImage*)imageOfKBIconRuleRandomizeOn;
+ (UIImage*)imageOfKBIconRulePlace0;
+ (UIImage*)imageOfKBIconRulePlace1;
+ (UIImage*)imageOfKbIconRulePlace2;
+ (UIImage*)imageOfKBIconRulePlace3;
+ (UIImage*)imageOfKBIconRulePlace4;
+ (UIImage*)imageOfKBIconRulePlace5;
+ (UIImage*)imageOfKBIconRulePlaceEmpty;
+ (UIImage*)imageOfKBIconBaseAngle;
+ (UIImage*)imageOfKPathArrow;
+ (UIImage*)imageOfSKTextureTurtleJoint;
+ (UIImage*)imageOfKMBFilterBackground;
+ (UIImage*)imageOfKLibraryCellBackgroundImage;
+ (UIImage*)imageOfKMBFilterBackground3;
+ (UIImage*)imageOfLineEditControllerWithFrame: (CGRect)frame;
+ (UIImage*)imageOfControlSliderBackgroundWithFrame: (CGRect)frame;
+ (UIImage*)imageOfIPad76;
+ (UIImage*)imageOfAppStore1024WithCORNERRADIUS: (CGFloat)cORNERRADIUS;
+ (UIImage*)imageOfIcon40;
+ (UIImage*)imageOfIPadBeta76;
+ (UIImage*)imageOfIConBeta40;
+ (UIImage*)imageOfICon60;
+ (UIImage*)imageOfIConBeta60;
+ (UIImage*)imageOfIPadDebug;
+ (UIImage*)imageOfIConDebug60;
+ (UIImage*)imageOfIConDebug40;
+ (UIImage*)imageOfIConDebug29;
+ (UIImage*)imageOfIConBeta29;
+ (UIImage*)imageOfICon29;
+ (UIImage*)imageOfICon50;
+ (UIImage*)imageOfDocumentThumbnailPlaceholder1024;
+ (UIImage*)imageOfPremiumUpgradeImage;
+ (UIImage*)imageOfMetalPak1UpgradeImage;

@end



@interface NSShadow (PaintCodeAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;
- (void)set;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
