//
//  FractalScapeIconSet.h
//  FractalScape
//
//  Created by Taun Chapman on 09/03/14.
//  Copyright (c) 2014 MOEDAE LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface FractalScapeIconSet : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarLineColorIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarFillColorIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarLinePropertiesIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarRulesIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarCopyIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarAppearanceIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDrawLineTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDrawDotTargets;

// Colors
+ (UIColor*)symbolFillColor;
+ (UIColor*)white5050;
+ (UIColor*)transformActionColor;

// Drawing Methods
+ (void)drawTabBarLineColorIcon;
+ (void)drawTabBarFillColorIcon;
+ (void)drawTabBarLinePropertiesIcon;
+ (void)drawTabBarRulesIcon;
+ (void)drawToolBarCopyIcon;
+ (void)drawToolBarAppearanceIcon;
+ (void)drawKBIconRuleDrawLine;
+ (void)drawKBIconRuleMoveByLine;
+ (void)drawKBIconRuleDrawDot;
+ (void)drawKBIconRuleDecrementLineWidth;
+ (void)drawKBIconRuleIncrementLineWidth;
+ (void)drawKBIconRuleOpenPolygon;
+ (void)drawKBIconRuleClosePolygon;
+ (void)drawKBIconRuleDecrementAngle;
+ (void)drawKBIconRuleIncrementAngle;
+ (void)drawKBIconRuleRotateC;
+ (void)drawKBIconRuleRotateCC;
+ (void)drawKBIconRulePush;
+ (void)drawKBIconRulePop;
+ (void)drawKBIconRuleSwapRotation;
+ (void)drawKBIconRuleReverseDirection;
+ (void)drawKBIconRuleFillOn;
+ (void)drawKBIconRuleFillOff;
+ (void)drawKBIconRuleUpscaleLineLength;
+ (void)drawKBIconRuleDownscaleLineLength;
+ (void)drawKBIconRuleStrokeOff;
+ (void)drawKBIconRuleStrokeOn;
+ (void)drawKBIconRuleRandomizeOff;
+ (void)drawKBIconRuleRandomizeOn;
+ (void)drawKBIconRulePlace0;
+ (void)drawKBIconRulePlace1;
+ (void)drawKBIconRulePlace2;
+ (void)drawKBIconRulePlace3;
+ (void)drawKBIconRulePlace4;
+ (void)drawKBIconRulePlace5;
+ (void)drawElements;

// Generated Images
+ (UIImage*)imageOfTabBarLineColorIcon;
+ (UIImage*)imageOfTabBarFillColorIcon;
+ (UIImage*)imageOfTabBarLinePropertiesIcon;
+ (UIImage*)imageOfTabBarRulesIcon;
+ (UIImage*)imageOfToolBarCopyIcon;
+ (UIImage*)imageOfToolBarAppearanceIcon;
+ (UIImage*)imageOfKBIconRuleDrawLine;
+ (UIImage*)imageOfKBIconRuleDrawDot;

@end
