//
//  FractalScapeIconSet.h
//  FractalScape
//
//  Created by Taun Chapman on 2021-05-10.
//  Copyright © 2021 MOEDAE LLC. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



@interface NSShadow (FractalScapeIconSetAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;

- (void)set;

@end



typedef NS_ENUM(NSInteger, FractalScapeIconSetResizingBehavior)
{
    FractalScapeIconSetResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    FractalScapeIconSetResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    FractalScapeIconSetResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    FractalScapeIconSetResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

};

extern CGRect FractalScapeIconSetResizingBehaviorApply(FractalScapeIconSetResizingBehavior behavior, CGRect rect, CGRect target);


@interface FractalScapeIconSet : NSObject

// iOS Controls Customization Outlets
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarLinePropertiesIconTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarRulesIconTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarPageColorIconTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarCopyIconTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarAppearanceIconTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarFullScreenIconTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarFullScreenIconOffTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* toolBarCopyIconTintedTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDrawLineTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleMoveByLineTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDrawDotTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDecrementLineWidthTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleIncrementLineWidthTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconCurveSymbolTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleClosePolygonTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDecrementAngleTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleIncrementAngleTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleRotateCTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleRotateCCTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePushTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePopTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleSwapRotationTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleReverseDirectionTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleFillOnTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleFillOffTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleUpscaleLineLengthTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleDownscaleLineLengthTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleStrokeOffTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleStrokeOnTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleRandomizeOffTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRuleRandomizeOnTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlace0Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlace1Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kbIconRulePlace2Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlace3Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlace4Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlace5Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconRulePlaceEmptyTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kBIconBaseAngleTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kPathArrowTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* sKTextureTurtleJointTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kMBFilterBackgroundTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kLibraryCellBackgroundImageLightTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kMBFilterBackground3Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* kLibraryCellBackgroundImageDarkTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPad76Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon40Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPadBeta76Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConBeta40Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iCon60Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConBeta60Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPadDebug76Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConDebug60Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConDebug40Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConDebug29Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConBeta29Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iCon29Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iCon50Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* documentThumbnailPlaceholder1024Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPadBetaDebug76Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConBetaDebug60Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConBetaDebug40Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConBetaDebug29Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPad167Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPadBeta167Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPadDebug167Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPadBetaDebug167Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConBetaDebug20Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConDebug20Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iConBeta20Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* iCon20Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* mac16Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* mac32Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* mac64Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* mac128Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* mac256Targets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* mac512Targets;

// Colors
+ (UIColor*)symbolFillColor;
+ (UIColor*)ruleGhostLineColor;
+ (UIColor*)transformActionColor;
+ (UIColor*)groupBorderColor;
+ (UIColor*)selectionBackgroundColor;
+ (UIColor*)betaColor;
+ (UIColor*)tutorialOverlayColor;
+ (UIColor*)tintColor;
+ (UIColor*)tintColorWithAlpha;

// Shadows
+ (NSShadow*)topShadow;
+ (NSShadow*)dropShadowInner;

// Drawing Methods
+ (void)drawTabBarLinePropertiesIcon;
+ (void)drawTabBarRulesIcon;
+ (void)drawTabBarPageColorIcon;
+ (void)drawToolBarCopyIcon;
+ (void)drawToolBarAppearanceIcon;
+ (void)drawToolBarFullScreenIcon;
+ (void)drawToolBarHUDScreenIconOld;
+ (void)drawToolBarFullScreenIcon2;
+ (void)drawToolBarHUDScreenIcon2;
+ (void)drawToolBarFullScreenIconOff;
+ (void)drawToolBarPlay;
+ (void)drawToolBarDoubleDragSymbolOn;
+ (void)drawToolBarDoubleDragSymbolOff;
+ (void)drawToolBarJointRotationSymbol;
+ (void)drawToolBarIncrementsButtonSymbol;
+ (void)drawToolBarBaseRotationButtonSymbol;
+ (void)drawToolBarPlayTinted;
+ (void)drawToolBarCopyIconTinted;
+ (void)drawKBIconRuleDrawLine;
+ (void)drawKBIconRuleDrawLineWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawKBIconRuleMoveByLine;
+ (void)drawKBIconRuleDrawDot;
+ (void)drawKBIconRuleDecrementLineWidth;
+ (void)drawKBIconRuleIncrementLineWidth;
+ (void)drawKBIconCurveSymbol;
+ (void)drawKBIconCurveSymbolWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawKBIconRuleClosePolygon;
+ (void)drawKBIconRuleDecrementAngle;
+ (void)drawKBIconRuleDecrementAngleWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawKBIconRuleIncrementAngle;
+ (void)drawKBIconRuleRotateC;
+ (void)drawKBIconRuleRotateCC;
+ (void)drawKBIconRuleRotateCCWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawKBIconRulePush;
+ (void)drawKBIconRulePushWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawKBIconRulePop;
+ (void)drawKBIconRuleSwapRotation;
+ (void)drawKBIconRuleReverseDirection;
+ (void)drawKBIconRuleFillOn;
+ (void)drawKBIconRuleFillOff;
+ (void)drawKBIconRuleUpscaleLineLength;
+ (void)drawKBIconRuleDownscaleLineLength;
+ (void)drawKBIconRuleStrokeOff;
+ (void)drawKBIconRuleStrokeOn;
+ (void)drawKBIconRuleRandomizeOff;
+ (void)drawKBIconRuleRandomizeOn;
+ (void)drawKBIconRulePlace0;
+ (void)drawKBIconRulePlace1;
+ (void)drawKbIconRulePlace2;
+ (void)drawKBIconRulePlace3;
+ (void)drawKBIconRulePlace4;
+ (void)drawKBIconRulePlace5;
+ (void)drawElements;
+ (void)drawKBIconRuleDrawDotFilled;
+ (void)drawKBIconRuleNextColor;
+ (void)drawKBIconRulePreviousColor;
+ (void)drawKBIconRulePlaceEmpty;
+ (void)drawKBIconRuleNextFillColor;
+ (void)drawKBIconRulePreviousFillColor;
+ (void)drawKBIconRuleDrawLineVarD;
+ (void)drawKBIconRuleSymbolArrowHead;
+ (void)drawKBIconRuleSymbolArrowHeadWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawKbIconRuleCurvePoint;
+ (void)drawKBIconRuleCurveC;
+ (void)drawKBIconRuleCurveCC;
+ (void)drawKBIconRulePushOld;
+ (void)drawKBIconRulePullOld;
+ (void)drawKBIconBaseAngle;
+ (void)drawKBIconBaseAngleWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawKBIconBaseAngleSmallWithFrame: (CGRect)frame;
+ (void)drawKBIconRuleDecrementAngleSmallWithFrame: (CGRect)frame;
+ (void)drawKBIconRuleRotateCCSmallWithFrame: (CGRect)frame;
+ (void)drawKBIconRuleDrawPath;
+ (void)drawKBIconRuleClosePath;
+ (void)drawKBIconRuleOpenPolygon;
+ (void)drawKBIconRuleDecrementLineWidth90;
+ (void)drawKBIconRuleDrawLineLeft;
+ (void)drawKPathArrow;
+ (void)drawSKTextureTurtleJoint;
+ (void)drawKNorthArrow;
+ (void)drawRatingBarImage;
+ (void)drawRatingStarSymbol;
+ (void)drawRatingStarSymbolWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawKMBFilterBackground;
+ (void)drawKMBFilterBackground2;
+ (void)drawKLibraryCellBackgroundImageLight;
+ (void)drawKRowDeleteSwipeIcon;
+ (void)drawKRowAddSwipeIcon;
+ (void)drawKMBFilterBackground3;
+ (void)drawKMBFilterBackground4;
+ (void)drawKRowDeleteSwipeIcon2;
+ (void)drawKRowAddSwipeIcon2;
+ (void)drawWatermark;
+ (void)drawKLibraryCellBackgroundImageDark;
+ (void)drawLineEditControllerWithFrame: (CGRect)frame;
+ (void)drawKCGLineCapSquareIcon;
+ (void)drawKCGLineCapRoundIcon;
+ (void)drawKCGLineCapButtIcon;
+ (void)drawKCGLineJoinMiterIcon;
+ (void)drawKCGLineJoinRoundIcon;
+ (void)drawKCGLineJoinBevelIcon;
+ (void)drawControlSliderBackgroundWithFrame: (CGRect)frame;
+ (void)drawBetaSymbol;
+ (void)drawBetaSymbolWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawAlphaSymbol;
+ (void)drawAlphaSymbolWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawLowresBushSymbol;
+ (void)drawLowresBushSymbolWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawLowresBushTemplate;
+ (void)drawDocumentThumbnailPlaceholder130;
+ (void)drawLowresBushTemplateTinted;
+ (void)drawBetaDbgSymbol;
+ (void)drawBetaDbgSymbolWithFrame: (CGRect)targetFrame resizing: (FractalScapeIconSetResizingBehavior)resizing;
+ (void)drawIntroArrowDuplicate;
+ (void)drawDefaultIntroArrow2;
+ (void)drawIntroArrowShare;
+ (void)drawIntroArrowPlay;
+ (void)drawCanvas1;

// Generated Images
+ (UIImage*)imageOfTabBarLinePropertiesIcon;
+ (UIImage*)imageOfTabBarRulesIcon;
+ (UIImage*)imageOfTabBarPageColorIcon;
+ (UIImage*)imageOfToolBarCopyIcon;
+ (UIImage*)imageOfToolBarAppearanceIcon;
+ (UIImage*)imageOfToolBarFullScreenIcon;
+ (UIImage*)imageOfToolBarFullScreenIconOff;
+ (UIImage*)imageOfToolBarCopyIconTinted;
+ (UIImage*)imageOfKBIconRuleDrawLine;
+ (UIImage*)imageOfKBIconRuleMoveByLine;
+ (UIImage*)imageOfKBIconRuleDrawDot;
+ (UIImage*)imageOfKBIconRuleDecrementLineWidth;
+ (UIImage*)imageOfKBIconRuleIncrementLineWidth;
+ (UIImage*)imageOfKBIconCurveSymbol;
+ (UIImage*)imageOfKBIconRuleClosePolygon;
+ (UIImage*)imageOfKBIconRuleDecrementAngle;
+ (UIImage*)imageOfKBIconRuleIncrementAngle;
+ (UIImage*)imageOfKBIconRuleRotateC;
+ (UIImage*)imageOfKBIconRuleRotateCC;
+ (UIImage*)imageOfKBIconRulePush;
+ (UIImage*)imageOfKBIconRulePop;
+ (UIImage*)imageOfKBIconRuleSwapRotation;
+ (UIImage*)imageOfKBIconRuleReverseDirection;
+ (UIImage*)imageOfKBIconRuleFillOn;
+ (UIImage*)imageOfKBIconRuleFillOff;
+ (UIImage*)imageOfKBIconRuleUpscaleLineLength;
+ (UIImage*)imageOfKBIconRuleDownscaleLineLength;
+ (UIImage*)imageOfKBIconRuleStrokeOff;
+ (UIImage*)imageOfKBIconRuleStrokeOn;
+ (UIImage*)imageOfKBIconRuleRandomizeOff;
+ (UIImage*)imageOfKBIconRuleRandomizeOn;
+ (UIImage*)imageOfKBIconRulePlace0;
+ (UIImage*)imageOfKBIconRulePlace1;
+ (UIImage*)imageOfKbIconRulePlace2;
+ (UIImage*)imageOfKBIconRulePlace3;
+ (UIImage*)imageOfKBIconRulePlace4;
+ (UIImage*)imageOfKBIconRulePlace5;
+ (UIImage*)imageOfKBIconRulePlaceEmpty;
+ (UIImage*)imageOfKBIconBaseAngle;
+ (UIImage*)imageOfKPathArrow;
+ (UIImage*)imageOfSKTextureTurtleJoint;
+ (UIImage*)imageOfKMBFilterBackground;
+ (UIImage*)imageOfKLibraryCellBackgroundImageLight;
+ (UIImage*)imageOfKMBFilterBackground3;
+ (UIImage*)imageOfKLibraryCellBackgroundImageDark;
+ (UIImage*)imageOfLineEditControllerWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfControlSliderBackgroundWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfIPad76;
+ (UIImage*)imageOfAppStore1024WithCORNERRADIUS: (CGFloat)cORNERRADIUS;
+ (UIImage*)imageOfIcon40;
+ (UIImage*)imageOfIPadBeta76;
+ (UIImage*)imageOfIConBeta40;
+ (UIImage*)imageOfICon60;
+ (UIImage*)imageOfIConBeta60;
+ (UIImage*)imageOfIPadDebug76;
+ (UIImage*)imageOfIConDebug60;
+ (UIImage*)imageOfIConDebug40;
+ (UIImage*)imageOfIConDebug29;
+ (UIImage*)imageOfIConBeta29;
+ (UIImage*)imageOfICon29;
+ (UIImage*)imageOfICon50;
+ (UIImage*)imageOfDocumentThumbnailPlaceholder1024;
+ (UIImage*)imageOfIPadBetaDebug76;
+ (UIImage*)imageOfIConBetaDebug60;
+ (UIImage*)imageOfIConBetaDebug40;
+ (UIImage*)imageOfIConBetaDebug29;
+ (UIImage*)imageOfIPad167;
+ (UIImage*)imageOfIPadBeta167;
+ (UIImage*)imageOfIPadDebug167;
+ (UIImage*)imageOfIPadBetaDebug167;
+ (UIImage*)imageOfIConBetaDebug20;
+ (UIImage*)imageOfIConDebug20;
+ (UIImage*)imageOfIConBeta20;
+ (UIImage*)imageOfICon20;
+ (UIImage*)imageOfMac16;
+ (UIImage*)imageOfMac32;
+ (UIImage*)imageOfMac64;
+ (UIImage*)imageOfMac128;
+ (UIImage*)imageOfMac256;
+ (UIImage*)imageOfMac512;

@end
